#ifndef _FIR_INT_H_
#define _FIR_INT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdint.h>

/*
 *
 * Coefficient generated by Iowa Hills Software FIR Filter Designer Ver. 7.0
 * http://www.iowahills.com/
 * http://www.iowahills.com/5FIRFiltersPage.html
 * http://www.iowahills.com/8DownloadPage.html
 *
*/

extern const double rect48_minph_kaiser4_fc50[];
extern const double rect32_minph_kaiser6_fc50[];
extern const double rect32_minph_kaiser4_fc50[];
extern const double rect32_minph_kaiser2_fc50[];
extern const double rect24_minph_kaiser6_fc50[];
extern const double rect20_minph_kaiser6_fc50[];
extern const double rect16_minph_kaiser6_fc50[];

typedef struct
{
	uint32_t taps;
	uint32_t step;
	uint32_t coeff_depth;
	int32_t *coeff;
	int16_t *out;
} fir_int_ctx_t;

void fir_int_init(fir_int_ctx_t *ctx, double *coeff_f, int32_t *coeff_i, uint32_t taps, int16_t *out, uint32_t coeff_depth);
void fir_int_calc(fir_int_ctx_t *ctx, int16_t *in, uint32_t len);
void fir_int_bystep_calc(fir_int_ctx_t *ctx, int16_t *in);

#ifdef __cplusplus
}
#endif

#endif
